#Configurações para spring data-jpa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vdlab
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: email-para-serviço@gmail.com
    password: a-senha-do-email
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /

#Configurações socket para FPGA
fpga:
  host: localhost
  port: 2540
  quantidadePlacas: 2 # Importante editar de acordo com a quantidade de placas a serem ligadas na máquina

#Configuraçao com rotas do raspberry
feedback:
  urlsMonitoramento: http://192.168.1.13:8081, http://192.168.1.13:8082

  iniciarVideo: http://192.168.1.13:809
  pararVideo: http://192.168.1.13:810

arquivos:
  vdlab: arquivos/
  pdf: arquivos/pdf/
  libs: arquivos/libs/

comandos:
  scripts:
    programmer: /home/weslley/Documentos/TADS/TCC/testes-tcl/programmer.sh
    getPlacas: /home/weslley/Documentos/TADS/TCC/testes-tcl/get_fpga_order.sh
    tclServer: /home/weslley/Documentos/TADS/TCC/testes-tcl/vdlab_connection.sh
